// SPDX-License-Identifier: GPL-3.0-only
package helium314.keyboard.unicode

/** Look-alike variants offered per character in the character customization screen. Ported from CMkey CharacterCatalog. */
object CharacterCatalog {
    val entries: Map<Char, List<String>> = linkedMapOf(
        'A' to listOf("Α", "ᗅ", "Λ", "ᗋ", "Ꭿ", "ᗩ", "₳"),
        'a' to listOf("а", "ɑ", "𝔞", "ᥑ", "⩜"),
        'B' to listOf("Β", "В", "₿", "β", "Ᏸ", "ᗷ"),
        'b' to listOf("ᏸ", "ᑲ", "Ь", "ь", "в", "ⲃ", "ᏼ"),
        'C' to listOf("Ϲ", "С", "Ⅽ", "Ҫ"),
        'c' to listOf("ϲ", "с", "ᥴ", "ⅽ"),
        'D' to listOf("ᗪ", "ᗞ"),
        'd' to listOf("Ԁ", "ԁ", "ᑯ", "𐓰", "ძ"),
        'Đ' to listOf("Ɖ"),
        'đ' to listOf("ᵭ", "₫", "ƌ", "𐓱", "ᴆ", "Ꮷ", "ð"),
        'E' to listOf("Ԑ", "Ε"),
        'e' to listOf("ᥱ", "ᧉ", "ԑ", "ε", "ϵ", "є"),
        'F' to listOf("Ϝ", "Ғ", "ᖴ"),
        'f' to listOf("𑫚", "ϝ", "ғ"),
        'G' to listOf("Ԍ", "Ⴚ", "Ᏽ", "Ꮐ", "₲"),
        'g' to listOf("ԍ", "ց", "𝔤", "ᏽ"),
        'H' to listOf("Η", "Н", "Ң", "Ҥ", "ዘ"),
        'h' to listOf("н", "ң", "ҥ", "ⲏ", "Ꮒ", "ዞ"),
        'I' to listOf("Ι", "Ⲓ"),
        'i' to listOf("ι", "ɩ", "Ꭵ", "ї", "ⲓ", "𝜄", "เ"),
        'J' to listOf("Ј", "յ", "Ϳ", "Ꭻ"),
        'j' to listOf("ϳ", "ј"),
        'K' to listOf("Κ", "Қ", "₭", "Ⲕ", "Ꮶ"),
        'k' to listOf("ⲕ", "κ", "к", "қ"),
        'L' to listOf("ᒪ", "Ꮮ", "ᥨ", "Լ", "Ⅼ"),
        'l' to listOf("ւ", "𝔩", "ℓ", "ⅼ"),
        'M' to listOf("Μ", "Ϻ", "Ⲙ", "ᙏ"),
        'm' to listOf("ϻ", "ʍ", "ⲙ", "ꪔ"),
        'N' to listOf("Ν", "Ͷ", "𑪾", "Ⲛ"),
        'n' to listOf("ⲛ", "ͷ", "ո", "η", "ռ", "ⴖ", "ᥒ", "ท"),
        'O' to listOf("ϴ", "Ο", "θ", "Ѻ"),
        'o' to listOf("ο", "σ", "ᦞ", "ѻ", "໐"),
        'P' to listOf("Ρ", "Р", "ᑭ", "Ҏ"),
        'p' to listOf("𝜌", "ҏ", "ρ", "ᑭ"),
        'Q' to listOf("Ԛ", "ⵕ"),
        'q' to listOf("ᤚ", "ᨾ", "ᑫ", "ԛ", "գ"),
        'R' to listOf("Я", "R", "Ʀ", "Ꮢ", "ᖇ", "Ꭱ"),
        'r' to listOf("я", "ʀ", "г"),
        'S' to listOf("Ѕ", "Տ", "ჽ", "Ꮪ", "\$"),
        's' to listOf("ѕ", "᥉", "ട", "ຣ"),
        'T' to listOf("Ͳ", "Т", "Τ", "Ꭲ", "₸", "Ҭ"),
        't' to listOf("ϯ", "τ", "ꚍ", "ҭ"),
        'U' to listOf("Ա", "Ս", "ᥩ", "𝈈"),
        'u' to listOf("υ", "ᥙ", "ս", "ບ"),
        'V' to listOf("Ѵ", "𝈍", "Ꮴ"),
        'v' to listOf("ν", "𝜈", "ѵ", "᥎", "ꪚ"),
        'W' to listOf("Ԝ", "ᗯ", "Ꮃ", "Ꮤ", "ᙎ"),
        'w' to listOf("ꪝ", "ԝ", "ѡ", "ω", "ധ", "𝈢"),
        'X' to listOf("Χ", "Х", "Ӽ", "Ⲭ", "ⵋ", "χ"),
        'x' to listOf("х", "ӽ", "᥊", "ⲭ", "ꪎ", "ӿ"),
        'Y' to listOf("Υ", "У", "ϒ", "Ⲩ", "ⲩ"),
        'y' to listOf("γ", "у", "ყ", "ⴘ"),
        'Z' to listOf("Ζ", "Ⴭ", "𝛧", "𑪽"),
        'z' to listOf("ⲍ", "ⴭ", "ᤏ", "ƶ"),
    )
}
